AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false