AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/*_pb.rb'
    - 'spec/*_helper.rb'

Metrics/BlockLength:
  ExcludedMethods: ['describe']

Metrics/AbcSize:
  Max: 20

Rails:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never