FROM ruby:2.4

EXPOSE 3000

RUN apt-get update \
      && apt-get install -qq -y build-essential nodejs libpq-dev postgresql-client-9.4 --fix-missing --no-install-recommends

ENV INSTALL_PATH /opt/zmora-server
ENV RAILS_ENV development
RUN mkdir -p $INSTALL_PATH

WORKDIR $INSTALL_PATH

COPY . .

RUN bin/bundle install --path vendor/bundle

CMD ["/bin/bash", "-c", "rm -f /tmp/server.pid && bin/bundle install --path vendor/bundle && bin/bundle exec -- rails db:create db:migrate && bin/bundle exec -- rails s --pid /tmp/server.pid"]