# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: judge.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Task" do
    optional :task_id, :int64, 1
    optional :configuration, :string, 2
    repeated :files, :message, 3, "Task.File"
    repeated :tests, :message, 4, "Task.Test"
  end
  add_message "Task.File" do
    optional :name, :string, 1
    optional :content, :bytes, 2
  end
  add_message "Task.Test" do
    optional :test_id, :int64, 1
    optional :input, :string, 2
    optional :output, :string, 3
    optional :time_limit, :int64, 4
    optional :ram_limit, :int64, 5
  end
  add_message "TaskResult" do
    optional :result_id, :int64, 1
    optional :compilation_log, :string, 2
    repeated :tests_results, :message, 3, "TaskResult.TestResult"
  end
  add_message "TaskResult.TestResult" do
    optional :source_test_id, :int64, 1
    optional :status, :enum, 2, "TaskResult.Status"
    optional :execution_time, :int64, 3
    optional :ram_usage, :int64, 4
  end
  add_enum "TaskResult.Status" do
    value :OK, 0
    value :RTE, 1
    value :MEM, 2
    value :TLE, 3
    value :ANS, 4
    value :CME, 5
  end
end

Task = Google::Protobuf::DescriptorPool.generated_pool.lookup("Task").msgclass
Task::File = Google::Protobuf::DescriptorPool.generated_pool.lookup("Task.File").msgclass
Task::Test = Google::Protobuf::DescriptorPool.generated_pool.lookup("Task.Test").msgclass
TaskResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("TaskResult").msgclass
TaskResult::TestResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("TaskResult.TestResult").msgclass
TaskResult::Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("TaskResult.Status").enummodule
